### Numpy Assignment No.1

#### Q1: Basic Array Operations


In [41]:
import pandas as pd
import numpy as np

In [42]:
#Create a 1D array, a 2D array, and a 3D array.
# One Demensional Array
oneD = np.array([1, 2, 3, 4]) # 1D array 
print(oneD) 

[1 2 3 4]


In [43]:
# Two Demensional Array
twoD = np.array([[1, 2], [3, 4]]) # 2D Array
#twoD
print(twoD)

[[1 2]
 [3 4]]


In [44]:
# Three Demensional Array
threeD = np.array([[2, 4], [6, 8], [10, 12]]) # 3D Array
print(threeD)
threeD

[[ 2  4]
 [ 6  8]
 [10 12]]


array([[ 2,  4],
       [ 6,  8],
       [10, 12]])

In [45]:
#Perform slicing operations on arrays.
slicing = np.arange(10)**3 # create array cube by arange function 
#print(slicing)
#print(slicing[4:8]) #array slincing 
sli = np.arange(10)**3
sli[2:6:2]
sli
slicing[:8:2] = -1000 
#slicing

In [46]:
#Perform basic arithmetic operations on arrays (addition, subtraction, multiplication, division)
art1 = np.array([[2, 4, 6],[1, 2, 3]])
art2 = np.array([[1, 3, 5],[4, 5, 6]])
art3 = np.array([[6, 7, 8],[2, 6, 10]])
art1 + art2 + art3 # Addition of array

array([[ 9, 14, 19],
       [ 7, 13, 19]])

In [47]:
art1 - art2 - art3 # Subtraction of array


array([[ -5,  -6,  -7],
       [ -5,  -9, -13]])

In [48]:
art1 * art2 * art3 # Multiplication of array


array([[ 12,  84, 240],
       [  8,  60, 180]])

In [49]:
art1 / art2 / art3 # division of array


array([[0.33333333, 0.19047619, 0.15      ],
       [0.125     , 0.06666667, 0.05      ]])

#### Q2: Array Creation and Manipulation


In [50]:
#Create arrays using different functions: arange, linspace, zeros, ones, eye, random.
zero = np.zeros(5) # using simple zero function
print(zero)
zero = np.zeros((10,), dtype=int)
#zero = np.zeros((2,2), dtype=[('x', 'i4'), ('y', 'i4')]) # using zero function 
zero

[0. 0. 0. 0. 0.]


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [51]:
#Reshape an array.
arange_arr = np.arange(10,30,2) # create array between 10 to 30 
reshape_arr = arange_arr.reshape(2,5)
print("Arry is:", arange_arr)
print("Reshaped array is:", reshape_arr)

Arry is: [10 12 14 16 18 20 22 24 26 28]
Reshaped array is: [[10 12 14 16 18]
 [20 22 24 26 28]]


In [52]:
#Concatenate and split arrays.
arr1 = np.array([4, 6, 8, 10]) # create Array one
arr2 = np.array([1, 2, 3, 4]) # create array two
concatenate_arr = np.concatenate((arr1,arr2), axis= 0) # concatenate both array with concatenate function
print("concatenate array:", concatenate_arr)

concatenate array: [ 4  6  8 10  1  2  3  4]


#### Q3: Statistical Operations

In [61]:
#Compute mean, median, variance, and standard deviation of an array.
# Mean standard deviation of an array
state_arr = np.arange(50,100,5)  # create array value 10 between 50 to 160 
mean_arr = np.mean(state_arr) # make mean of array with mean function
print("Original array: ", state_arr)
print("Mean: ", mean_arr)

Original array:  [50 55 60 65 70 75 80 85 90 95]
Mean:  72.5


In [71]:
# Median standard deviation of an array
state_arr1 = np.arange(1,36,2) # create arry of 18 value from 1 to 36
reshape_arr1 = state_arr1.reshape(3,6) # reshape the arry
median_arr = np.median(reshape_arr1, axis=0) # median of arry
print("original of the array is: ", state_arr)
print("reshaped array is: ", reshape_arr1)
print("Median of the array is: ", median_arr)


original of the array is:  [ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35]
reshaped array is:  [[ 1  3  5  7  9 11]
 [13 15 17 19 21 23]
 [25 27 29 31 33 35]]
Median of the array is:  [13. 15. 17. 19. 21. 23.]


In [78]:
#variance standard deviation of an array
state_arr2 = np.arange(4,16,2)# create arry of 7 value from 4 to 16
variance = state_arr2.var() # apply vraience function
print("original array is: ", state_arr2)
print("Variance of the array is: ", variance)
print("direct variance", np.var([2, 4, 6])) # we can find direct varienace

original array is:  [ 4  6  8 10 12 14]
Variance of the array is:  11.666666666666666
direct variance 2.6666666666666665


In [84]:
#standard deviation of an array
state_arr3 = np.arange(20,80,4) # create random arry of 10 value from 20 to 80
#std = sqrt(mean(abs(x - x.mean())**2)) # std formula
sd = state_arr3.std() # standard deviation function
print("original array:",state_arr3)
print("standard deviation of array:",sd)

original array: [20 24 28 32 36 40 44 48 52 56 60 64 68 72 76]
standard deviation of array: 17.281975195754296


In [83]:
#Find the minimum and maximum values in an array along with their indices.
# minimum values in an array
arr3 = np.random.randint(20, 100, 10, dtype=int) 
mini = arr3.min()
print("Array: ", arr3)
print("Minimum value: ", mini)

Array:  [46 41 61 83 28 30 50 52 95 48]
Minimum value:  28


In [86]:
#maximum values in an array
arr3 = np.random.randint(20, 100, 10, dtype=int) 
maxi = arr3.max()
print("Array: ", arr3)
print("Max value: ", maxi)

Array:  [68 48 53 85 62 96 76 76 89 36]
Max value:  96


In [ ]:
#Compute the sum and product of array elements.


#### Q4: Broadcasting


In [ ]:
#Demonstrate broadcasting with examples of different shapes of arrays.

In [ ]:
#Explain the concept of broadcasting and how it works in NumPy.

#### Q5: Linear Algebra

In [ ]:
#Perform matrix multiplication.

In [ ]:
#Compute the determinant, inverse, and eigenvalues of a matrix.

In [ ]:
#Solve a system of linear equations.

#### Q6: Advanced Indexing and Slicing


In [ ]:
#Use Boolean indexing to filter an array.

In [ ]:
#Use fancy indexing to select specific elements from an array.

In [ ]:
#Perform advanced slicing operations.

#### Q7: Random Sampling

In [ ]:
#Generate random numbers from different distributions.

In [ ]:
#Create random samples from a dataset.

In [ ]:
#Perform random shuffling of an array.